'use client';
import {useEffect,useState,FormEvent} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Row=Record<string,any>;
const forms:Record<string,{endpoint:string;fields:string[]}>={
'Station':{endpoint:'/stations',fields:['name','code','region','district']},
'Staff':{endpoint:'/staff',fields:['name','email','password','role']},
'Fuel product':{endpoint:'/products',fields:['name','price']},
'Tank':{endpoint:'/tanks',fields:['name','product_id','capacity','stock','reorder']},
'Nozzle':{endpoint:'/nozzles',fields:['name','tank_id','meter']},
'Open shift':{endpoint:'/shifts',fields:['nozzle_id','attendant_id']},
'Delivery':{endpoint:'/deliveries',fields:['tank_id','reference','supplier','waybill_litres','received_litres','cost_per_litre']},
'Expense':{endpoint:'/expenses',fields:['description','amount']}}
const scopedForms=['Staff','Fuel product','Tank','Expense'];
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function Home(){
 const [token,setToken]=useState(''),[user,setUser]=useState<Row|null>(null),[stations,setStations]=useState<Row[]>([]),[station,setStation]=useState(''),[tab,setTab]=useState('Overview'),[data,setData]=useState<Row>({}),[shifts,setShifts]=useState<Row[]>([]),[summary,setSummary]=useState<Row>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function request(path:string,body?:Row,session=token){const r=await fetch(API+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(session?{Authorization:`Bearer ${session}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await r.json();if(!r.ok)throw new Error(typeof result.detail==='string'?result.detail:'Check the form values');return result;}
 async function refresh(){if(!station||!user)return;const q=`?station_id=${station}`;try{setData(await request('/inventory'+q));setShifts(await request('/shifts'+q));if(user.role!=='attendant')setSummary(await request('/dashboard'+q));}catch(e:any){setMessage(e.message)}}
 useEffect(()=>{refresh()},[station,user]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const fd=new FormData(e.currentTarget);try{const s=await request('/auth/login',Object.fromEntries(fd), '');setToken(s.access_token);const u=await request('/auth/me',undefined,s.access_token);setUser(u);if(u.role==='attendant')setTab('Shifts');const rows=await request('/stations',undefined,s.access_token);setStations(rows);setStation(String(rows[0]?.id||''));}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage('');const form=e.currentTarget;const values:Row=Object.fromEntries(new FormData(form));if(scopedForms.includes(tab))values.station_id=Number(station);try{await request(forms[tab].endpoint,values);form.reset();setMessage('Record saved.');if(tab==='Station'){const rows=await request('/stations');setStations(rows);setStation(String(rows.at(-1).id));}await refresh();}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function submit(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();setBusy(true);try{await request(`/shifts/${id}/submit`,Object.fromEntries(new FormData(e.currentTarget)));await refresh();setMessage('Shift submitted for review.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 async function reconcile(id:number){setBusy(true);try{await request(`/shifts/${id}/reconcile`,{});await refresh();setMessage('Reconciled. Stock and meter updated.')}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 if(!user)return <main className="login"><div className="brand">F<span>F</span></div><p className="eyebrow">FUELFLOW GHANA</p><h1>Your station.<br/>Under control.</h1><p>Sign in to manage your fuel station operations.</p><form onSubmit={login}><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required autoComplete="current-password"/></label><button disabled={busy}>Sign in</button></form><p role="alert">{message}</p><small>New installation? Create the owner account using the setup command in the README.</small></main>;
 const owner=user.role==='owner', operations=['owner','manager','supervisor'].includes(user.role);
 const tabs=['Overview','Shifts','Inventory',...(owner?['Station','Staff','Fuel product','Tank','Nozzle']:[]),...(operations?['Open shift','Delivery']:[]),...(['owner','manager','accountant'].includes(user.role)?['Expense']:[])];
 return <div className="shell"><aside><div className="wordmark">FuelFlow<span>GHANA</span></div><p className="muted">Station operations</p><nav>{tabs.filter(x=>user.role!=='attendant'||x==='Shifts'||x==='Inventory').map(x=><button className={tab===x?'selected':''} key={x} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="profile"><strong>{user.name}</strong><small>{label(user.role)}</small><button onClick={()=>{setToken('');setUser(null);setMessage('')}}>Sign out</button></div></aside><main><header><div><p className="eyebrow">OPERATIONS WORKSPACE</p><h1>{tab}</h1></div><select aria-label="Station" value={station} onChange={e=>setStation(e.target.value)}><option value="">Select station</option>{stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></header><p className="notice" role="status">{message}</p>{!station&&<section className="card"><h2>Welcome to FuelFlow</h2><p>Create your first station, then add fuel products, tanks, nozzles and attendants.</p></section>}
 {tab==='Overview'&&user.role!=='attendant'&&station&&<><p className="muted">Today · reconciled shifts · GHS</p><div className="kpis">{['litres','expected','collections','variance','expenses'].map(k=><section className="card" key={k}><small>{label(k)}</small><h2>{Number(summary[k]||0).toLocaleString(undefined,{maximumFractionDigits:2})}{k==='litres'?' L':''}</h2></section>)}</div><section className="card"><h2>Stock alerts</h2>{summary.alerts?.length?summary.alerts.map((a:string)=><p className="warning" key={a}>{a}</p>):<p>No low stock alerts.</p>}</section><section className="card"><h2>Daily control</h2><p>Open a shift for an attendant, record closing readings and collections, then reconcile to post stock movements.</p><p className="muted">Collections include staff-confirmed cash, Mobile Money and card payments.</p></section></>}
 {tab==='Inventory'&&<>{['products','tanks','nozzles'].map(group=><section className="card" key={group}><h2>{label(group)}</h2><div className="tablewrap"><table><thead><tr>{(group==='products'?['id','name','price']:group==='tanks'?['id','name','product_id','capacity','stock','reorder']:['id','name','tank_id','meter']).map(k=><th key={k}>{label(k)}</th>)}</tr></thead><tbody>{data[group]?.map((r:Row)=><tr key={r.id}>{(group==='products'?['id','name','price']:group==='tanks'?['id','name','product_id','capacity','stock','reorder']:['id','name','tank_id','meter']).map(k=><td key={k}>{r[k]}</td>)}</tr>)}</tbody></table></div></section>)}</>}
 {tab==='Shifts'&&<div className="shiftgrid">{shifts.length===0&&<p>No shifts recorded.</p>}{shifts.map(s=><section className="card" key={s.id}><span className="badge">{s.status}</span><h2>Shift #{s.id} · Nozzle {s.nozzle_id}</h2><p>Opening: {s.opening} L · Price: GHS {s.price}/L</p>{s.status==='open'&&user.role!=='auditor'&&user.role!=='accountant'&&<form onSubmit={e=>submit(e,s.id)}>{['closing','cash','momo','card'].map(k=><label key={k}>{label(k)}<input name={k} type="number" min="0" step={k==='closing'?'0.001':'0.01'} required/></label>)}<button disabled={busy}>Submit readings</button></form>}{s.status!=='open'&&<p>{s.litres} L · Expected GHS {s.expected}<br/>Variance GHS {s.variance}</p>}{s.status==='submitted'&&operations&&<button disabled={busy} onClick={()=>reconcile(s.id)}>Approve reconciliation</button>}</section>)}</div>}
 {forms[tab]&&<section className="card formcard"><h2>{tab==='Open shift'?'Assign a nozzle and attendant':`Add ${tab.toLowerCase()}`}</h2><form onSubmit={create}>{forms[tab].fields.map(k=><label key={k}>{label(k)}{k==='role'?<select name={k}>{['manager','supervisor','attendant','accountant','auditor'].map(r=><option key={r}>{r}</option>)}</select>:<input name={k} required type={k==='password'?'password':k==='email'?'email':(/_id$|price|capacity|stock|reorder|meter|litres|amount/.test(k)?'number':'text')} step="any" min="0" minLength={k==='password'?12:undefined}/>}</label>)}<button disabled={busy||(!station&&tab!=='Station')}>Save {tab.toLowerCase()}</button></form><p className="muted">Find tank, product and nozzle IDs in Inventory. Staff IDs are returned by the staff API.</p></section>}
 </main></div>}
