'use client';
import {useEffect,useState,FormEvent} from 'react';
const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000';
type Row=Record<string,any>;
type Field={name:string;type?:string;options?:Row[];optional?:boolean;hint?:string};
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const localDate=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Accra'});
const money=(v:any)=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
function Table({rows,columns,actions}:{rows:Row[];columns:string[];actions?:(row:Row)=>React.ReactNode}){return <div className="tablewrap"><table><thead><tr>{columns.map(k=><th key={k}>{label(k)}</th>)}{actions&&<th>Actions</th>}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}>{columns.map(k=><td key={k}>{typeof r[k]==='boolean'?(r[k]?'Yes':'No'):r[k]??'—'}</td>)}{actions&&<td>{actions(r)}</td>}</tr>)}</tbody></table>{rows.length===0&&<p className="muted">No records yet.</p>}</div>}
function EntryForm({fields,onSave,button='Save',busy=false}:{fields:Field[];onSave:(values:Row)=>Promise<void>;button?:string;busy?:boolean}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const values:Row=Object.fromEntries(new FormData(form));for(const f of fields){if(values[f.name]===''&&f.optional)delete values[f.name];else if(f.type==='number'&&values[f.name]!=='')values[f.name]=Number(values[f.name]);}await onSave(values);}
return <form className="entryform" onSubmit={submit}>{fields.map(f=><label key={f.name}>{label(f.name)}{f.options?<select name={f.name} required={!f.optional}><option value="">Choose {label(f.name).toLowerCase()}</option>{f.options.map(o=><option key={o.id} value={o.id}>{o.name||o.label||o.registration}</option>)}</select>:f.type==='textarea'?<textarea name={f.name} required={!f.optional} maxLength={1000}/>:<input name={f.name} type={f.type||'text'} required={!f.optional} min={f.type==='number'?'0':undefined} step="any" maxLength={f.type==='password'?128:undefined} minLength={f.type==='password'?12:undefined} defaultValue={f.type==='date'?localDate():undefined} autoComplete={f.type==='password'?'new-password':undefined}/>} {f.hint&&<small>{f.hint}</small>}</label>)}<button disabled={busy}>{button}</button></form>}
export default function Home(){
 const [token,setToken]=useState(''),[user,setUser]=useState<Row|null>(null),[stations,setStations]=useState<Row[]>([]),[station,setStation]=useState(''),[tab,setTab]=useState('Overview'),[data,setData]=useState<Row>({}),[shifts,setShifts]=useState<Row[]>([]),[summary,setSummary]=useState<Row>({}),[staff,setStaff]=useState<Row[]>([]),[customers,setCustomers]=useState<Row[]>([]),[vehicles,setVehicles]=useState<Row[]>([]),[equipment,setEquipment]=useState<Row[]>([]),[maintenance,setMaintenance]=useState<Row[]>([]),[incidents,setIncidents]=useState<Row[]>([]),[expenses,setExpenses]=useState<Row[]>([]),[days,setDays]=useState<Row[]>([]),[auditRows,setAuditRows]=useState<Row[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[setup,setSetup]=useState(false),[setupChecked,setSetupChecked]=useState(false),[enroll,setEnroll]=useState(false),[mfa,setMfa]=useState<Row>({}),[recovery,setRecovery]=useState<string[]>([]),[statement,setStatement]=useState<Row|null>(null),[preview,setPreview]=useState<Row|null>(null),[report,setReport]=useState<Row|null>(null),[kind,setKind]=useState('daily'),[start,setStart]=useState(localDate()),[end,setEnd]=useState(localDate()),[config,setConfig]=useState('Station'),[editRepair,setEditRepair]=useState<Row|null>(null),[filterNozzle,setFilterNozzle]=useState(''),[filterAttendant,setFilterAttendant]=useState(''),[filterFuel,setFilterFuel]=useState(''),[filterPayment,setFilterPayment]=useState('');
 const owner=user?.role==='owner',ops=['owner','manager','supervisor'].includes(user?.role),finance=['owner','manager','accountant'].includes(user?.role),reader=user?.role!=='attendant';
 function clearSession(){setToken('');setUser(null);setStation('');setMfa({});setRecovery([]);setEnroll(false);setData({});setCustomers([]);setStatement(null);setReport(null);setPreview(null)}
 async function request(path:string,body?:Row,session=token){const response=await fetch(API+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(session?{Authorization:`Bearer ${session}`}:{})},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok){if(response.status===401&&session)clearSession();throw new Error(typeof result.detail==='string'?result.detail:'Check the form values');}return result;}
 async function run(work:()=>Promise<void>){setBusy(true);setMessage('');try{await work()}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 useEffect(()=>{request('/setup/status',undefined,'').then(r=>setSetup(r.requires_setup)).catch(()=>setMessage('The service is starting or unavailable. Please retry shortly.')).finally(()=>setSetupChecked(true))},[]);
 async function loadSession(session:string){const u=await request('/auth/me',undefined,session);setUser(u);const rows=await request('/stations',undefined,session);setStations(rows);setStation(String(rows[0]?.id||''));setTab(u.role==='attendant'?'Shifts':'Overview')}
 async function refresh(){if(!station||!user||enroll)return;const q=`?station_id=${station}`;try{const requests:[string,(r:any)=>void][]=[['/inventory',setData],['/shifts',setShifts],['/customers',setCustomers],['/vehicles',setVehicles],['/equipment',setEquipment],['/incidents',setIncidents]];if(reader)requests.push(['/dashboard',setSummary],['/expenses',setExpenses],['/maintenance',setMaintenance],['/business-days',setDays]);if(ops)requests.push(['/staff',setStaff]);if(owner){setAuditRows(await request('/audit'));}const results=await Promise.allSettled(requests.map(async([path,set])=>{const r=await request(path+q);set(r)}));for(const r of results)if(r.status==='rejected')setMessage(r.reason.message);}catch(e:any){setMessage(e.message)}}
 useEffect(()=>{setStatement(null);setReport(null);setPreview(null);refresh()},[station,user?.id,enroll]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const values:Row=Object.fromEntries(new FormData(e.currentTarget));if(!values.otp)delete values.otp;await run(async()=>{const session=await request('/auth/login',values,'');setToken(session.access_token);if(session.mfa_enrollment_required){setUser(await request('/auth/me',undefined,session.access_token));setEnroll(true);setTab('Security')}else{setEnroll(false);await loadSession(session.access_token)}})}
 async function save(path:string,values:Row){await run(async()=>{await request(path,values);setMessage('Saved successfully.');await refresh()})}
 async function bootstrap(values:Row){await run(async()=>{await request('/setup/owner',values,'');setSetup(false);setMessage('Owner created. Sign in to secure your account.')})}
 async function logout(){await run(async()=>{try{await request('/auth/logout',{})}finally{clearSession();setMessage('Signed out.')}})}
 async function mfaStart(values:Row){await run(async()=>{setMfa(await request('/auth/mfa/setup',values))})}
 async function mfaConfirm(values:Row){await run(async()=>{const result=await request('/auth/mfa/confirm',values);setToken(result.access_token);setRecovery(result.recovery_codes);setMfa({});setEnroll(false);await loadSession(result.access_token);setTab('Security');setMessage('Two-factor authentication enabled. Save your recovery codes securely.')})}
 async function approve(path:string){if(!window.confirm('Approve this record?'))return;await save(path,{})}
 async function viewStatement(id:number){await run(async()=>{setStatement(await request(`/customers/${id}/statement`))})}
 const reportQuery=()=>`station_id=${station}&start=${start}&end=${end}${kind==='sales'?(filterNozzle?`&nozzle_id=${filterNozzle}`:'')+(filterAttendant?`&attendant_id=${filterAttendant}`:'')+(filterFuel?`&product_id=${filterFuel}`:'')+(filterPayment?`&payment_method=${filterPayment}`:''):''}`;
 async function loadReport(){await run(async()=>setReport(await request(`/reports/${kind}?${reportQuery()}`)))}
 async function download(format:string){await run(async()=>{const response=await fetch(`${API}/reports/${kind}/export?${reportQuery()}&format=${format}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){const r=await response.json();throw new Error(typeof r.detail==='string'?r.detail:'Export failed')}const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`fuelflow-${kind}-${start}-${end}.${format}`;a.click();URL.revokeObjectURL(url)})}
 const f=(name:string,type='text',optional=false):Field=>({name,type,optional});const pick=(name:string,options:Row[],optional=false):Field=>({name,options,optional});const options=(values:string[])=>values.map(x=>({id:x,name:label(x)}));
 const dayFields=[f('business_date','date'),f('reason','text',true)];
 const settingForms:Record<string,{path:string;fields:Field[]}>= {
 Station:{path:'/stations',fields:[f('name'),f('code'),pick('region',options(['Ahafo','Ashanti','Bono','Bono East','Central','Eastern','Greater Accra','North East','Northern','Oti','Savannah','Upper East','Upper West','Volta','Western','Western North'])),f('district')]},
 'Fuel product':{path:'/products',fields:[f('name'),f('price','number')]},
 Tank:{path:'/tanks',fields:[f('name'),pick('product_id',data.products||[]),f('capacity','number'),f('stock','number'),f('reorder','number')]},
 Nozzle:{path:'/nozzles',fields:[f('name'),pick('tank_id',data.tanks||[]),f('meter','number')]}}
 if(!user)return <main className="login"><div className="brand">F</div><p className="eyebrow">FUELFLOW GHANA</p><h1>Your station.<br/>Under control.</h1>{setup&&setupChecked?<><p>Create your owner account using the installation access code.</p><EntryForm fields={[f('token','password'),f('name'),f('email','email'),f('password','password')]} onSave={bootstrap} button="Create owner account" busy={busy}/></>:<><p>Sign in to manage your fuel station operations.</p><form onSubmit={login}><label>Email<input name="email" type="email" required autoComplete="username"/></label><label>Password<input name="password" type="password" required maxLength={128} autoComplete="current-password"/></label><label>Authentication or recovery code <small>If enabled for your account</small><input name="otp" autoComplete="one-time-code" maxLength={64}/></label><button disabled={busy}>Sign in</button></form></>}<p role="alert">{message}</p><small>Sessions expire after 15 minutes of inactivity. Keep your installation code private.</small></main>;
 const tabs=enroll?['Security']:user.role==='attendant'?['Shifts','Credit sale','Incidents','Security']:['Overview','Shifts','Inventory','Customers','Expenses','Daily close','Maintenance','Incidents','Reports',...(ops?['Deliveries']:[]),...(owner?['Staff','Audit log','Settings']:[]),'Security'];
 const securityPanel=<section className="card formcard"><h2>Account security</h2>{recovery.length>0&&<div className="warning"><strong>Save these one-time recovery codes in a safe place.</strong><div className="recovery">{recovery.map(code=><code key={code}>{code}</code>)}</div><button onClick={()=>setRecovery([])}>I have saved the codes</button></div>}{user.mfa_enabled?<p>Two-factor authentication is enabled.</p>:<><p>{enroll?'Secure the owner account before accessing station records.':'Enable two-factor authentication using an authenticator app.'}</p>{!mfa.secret?<EntryForm fields={[{name:'password',type:'password'}]} onSave={mfaStart} button="Start authenticator setup" busy={busy}/>:<><p>In your authenticator app, add this setup key:</p><code className="secret">{mfa.secret}</code><p><a href={mfa.uri}>Open an authenticator app</a></p><EntryForm fields={[f('otp')]} onSave={mfaConfirm} button="Confirm authentication code" busy={busy}/></>}</>}{!enroll&&<><h3>Change password</h3><EntryForm fields={[f('current_password','password'),f('new_password','password')]} onSave={async values=>run(async()=>{await request('/auth/password',values);clearSession();setMessage('Password changed. Sign in again.')})} button="Change password and sign out" busy={busy}/></>}</section>;
 return <div className="shell"><aside><div className="wordmark">FuelFlow<span>GHANA</span></div><p className="muted">Station operations</p><nav>{tabs.map(x=><button className={tab===x?'selected':''} key={x} onClick={()=>setTab(x)}>{x}</button>)}</nav><div className="profile"><strong>{user.name}</strong><small>{label(user.role)}</small><button onClick={logout} disabled={busy}>Sign out</button></div></aside><main><header><div><p className="eyebrow">OPERATIONS WORKSPACE</p><h1>{tab}</h1></div>{!enroll&&<select aria-label="Station" value={station} onChange={e=>setStation(e.target.value)}><option value="">Select station</option>{stations.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}</header><p className="notice" role="status">{message}</p>{!station&&!enroll&&tab!=='Security'&&<section className="card"><h2>Welcome to FuelFlow</h2><p>Create your first station under Settings, then add products, tanks, nozzles and attendants.</p>{owner&&<button onClick={()=>{setTab('Settings');setConfig('Station')}}>Set up station</button>}</section>}
 {tab==='Security'&&securityPanel}
 {tab==='Overview'&&station&&<><p className="muted">Today · reconciled shifts · GHS</p><div className="kpis">{['litres','expected','collections','credit_sales','outstanding_credit','variance','expenses','active_shifts'].map(k=><section className="card" key={k}><small>{label(k)}</small><h2>{k==='active_shifts'?summary[k]||0:money(summary[k])}{k==='litres'?' L':''}</h2></section>)}</div><div className="twocol"><section className="card"><h2>Seven-day revenue</h2><div className="trend">{summary.trend?.map((r:Row)=><div className="trendrow" key={r.date}><small>{r.date.slice(5)}</small><div className="bar" style={{width:`${Math.max(1,Number(r.expected)/Math.max(1,...summary.trend.map((x:Row)=>Number(x.expected)))*70)}%`}}/><span>{money(r.expected)}</span></div>)}</div></section><section className="card"><h2>Alerts requiring attention</h2>{summary.alerts?.length?summary.alerts.map((a:string)=><p className="warning" key={a}>{a}</p>):<p>No current alerts.</p>}</section></div><p className="muted">Fuel collections exclude customer debt repayments. Dashboard expenses include approved records only.</p></>}
 {tab==='Inventory'&&station&&<>{['products','tanks','nozzles'].map(group=><section className="card" key={group}><h2>{label(group)}</h2><Table rows={data[group]||[]} columns={group==='products'?['id','name','price']:group==='tanks'?['id','name','capacity','stock','reorder']:['id','name','tank_id','meter']}/></section>)}{owner&&<section className="card formcard"><h2>Update a fuel price</h2><EntryForm fields={[pick('product_id',data.products||[]),f('price','number'),f('reason')]} onSave={async v=>{const id=v.product_id;delete v.product_id;await save(`/products/${id}/price`,v)}} busy={busy}/><small>New prices apply to newly opened shifts. Existing shifts retain their recorded price.</small></section>}{ops&&<section className="card formcard"><h2>Record physical tank stock</h2><p>Enter calibrated litres from your tank dip. This records a variance without changing book stock.</p><EntryForm fields={[pick('tank_id',data.tanks||[]),f('physical','number'),f('business_date','date'),f('notes','text',true)]} onSave={v=>save('/tank-readings',v)} busy={busy}/></section>}{owner&&<section className="card formcard"><h2>Authorize a stock adjustment</h2><EntryForm fields={[pick('tank_id',data.tanks||[]),f('physical','number'),f('business_date','date'),f('reference'),f('reason')]} onSave={async v=>{if(window.confirm('Post this adjustment to the stock ledger?'))await save('/stock-adjustments',v)}} busy={busy}/></section>}</>}
 {tab==='Shifts'&&station&&<>{ops&&<section className="card formcard"><h2>Open a shift</h2><EntryForm fields={[pick('nozzle_id',data.nozzles||[]),pick('attendant_id',staff.filter(s=>s.role==='attendant'&&s.active)),f('business_date','date')]} onSave={v=>save('/shifts',v)} busy={busy}/></section>}<div className="shiftgrid">{shifts.length===0&&<p>No shifts recorded.</p>}{shifts.map(s=><section className="card" key={s.id}><span className="badge">{s.status}</span><h2>Shift #{s.id} · {data.nozzles?.find((n:Row)=>n.id===s.nozzle_id)?.name||`Nozzle ${s.nozzle_id}`}</h2><p>{s.business_date} · Opening {s.opening} L<br/>Price GHS {s.price}/L</p>{s.status==='open'&&(ops||user.role==='attendant')&&<EntryForm fields={[f('closing','number'),f('cash','number'),f('momo','number'),f('card','number')]} onSave={v=>save(`/shifts/${s.id}/submit`,v)} button="Submit readings" busy={busy}/>} {s.status!=='open'&&<p>{s.litres} L · Expected GHS {money(s.expected)}<br/>Credit GHS {money(s.credit)} · Variance GHS {money(s.variance)}</p>}{s.status==='submitted'&&ops&&<button disabled={busy} onClick={()=>approve(`/shifts/${s.id}/reconcile`)}>Approve reconciliation</button>}</section>)}</div></>}
 {(tab==='Customers'||tab==='Credit sale')&&station&&<>{tab==='Customers'&&<section className="card"><h2>Customer accounts</h2><Table rows={customers} columns={['name','contact','credit_limit','balance','overdue','active']} actions={r=><button onClick={()=>viewStatement(r.id)}>Statement</button>}/></section>}{statement&&tab==='Customers'&&<section className="card"><h2>{statement.customer} statement</h2><p>Outstanding GHS {money(statement.totals.balance)} · Overdue GHS {money(statement.totals.overdue)}</p><Table rows={statement.rows} columns={['date','kind','reference','debit','credit','balance','vehicle','due_date']}/><button onClick={()=>window.print()}>Print statement</button></section>}{['owner','manager'].includes(user.role)&&<section className="card formcard"><h2>Approve a credit customer</h2><EntryForm fields={[f('name'),f('contact','text',true),f('credit_limit','number'),f('terms_days','number')]} onSave={v=>save('/customers',{...v,station_id:Number(station)})} busy={busy}/></section>}{(ops||user.role==='attendant')&&<section className="card formcard"><h2>Record a credit fuel sale</h2><EntryForm fields={[pick('customer_id',customers.filter(c=>c.active)),pick('shift_id',shifts.filter(s=>s.status==='open').map(s=>({...s,name:`Shift ${s.id} · Nozzle ${s.nozzle_id}`}))),f('registration'),f('driver'),f('reference'),f('litres','number'),pick('vehicle_id',vehicles.map(v=>({...v,name:v.registration})),true)]} onSave={v=>save('/credit/charges',v)} busy={busy}/><small>Credit is included automatically when the shift is submitted. Select a registered vehicle when the customer has a fleet authorization.</small></section>}{finance&&<section className="card formcard"><h2>Receive a customer debt payment</h2><EntryForm fields={[pick('customer_id',customers),f('amount','number'),pick('method',options(['cash','mtn_momo','telecel_cash','at_money','card','bank_transfer','other'])),f('reference'),f('business_date','date')]} onSave={v=>save('/credit/payments',v)} busy={busy}/></section>}{vehicles.length>0&&reader&&<section className="card"><h2>Fleet vehicles</h2><Table rows={vehicles} columns={['id','customer_id','registration','fuel_product_id','litre_limit','active']}/></section>}{['owner','manager'].includes(user.role)&&<section className="card formcard"><h2>Register a fleet vehicle</h2><EntryForm fields={[pick('customer_id',customers),f('registration'),pick('fuel_product_id',data.products||[]),{name:'litre_limit',type:'number',hint:'Maximum litres per business day'}]} onSave={v=>save('/vehicles',v)} busy={busy}/></section>}{owner&&<section className="card formcard"><h2>Update credit authorization</h2><EntryForm fields={[pick('customer_id',customers),f('credit_limit','number'),pick('active',[{id:'true',name:'Active'},{id:'false',name:'Disabled'}]),f('reason')]} onSave={async v=>{const id=v.customer_id;delete v.customer_id;v.active=v.active==='true';await save(`/customers/${id}/terms`,v)}} busy={busy}/></section>}</>}
 {tab==='Expenses'&&station&&<><section className="card"><h2>Expense approvals</h2><Table rows={expenses} columns={['business_date','description','amount','status']} actions={r=>r.status==='pending'&&['owner','manager'].includes(user.role)?<button disabled={busy} onClick={()=>approve(`/expenses/${r.id}/approve`)}>Approve</button>:null}/></section>{finance&&<section className="card formcard"><h2>Record an expense</h2><EntryForm fields={[f('description'),f('amount','number'),f('business_date','date')]} onSave={v=>save('/expenses',{...v,station_id:Number(station)})} busy={busy}/><small>Every expense requires owner or separate manager approval.</small></section>}</>}
 {tab==='Deliveries'&&station&&<section className="card formcard"><h2>Post a fuel delivery</h2><EntryForm fields={[pick('tank_id',data.tanks||[]),f('reference'),f('supplier'),f('waybill_litres','number'),f('received_litres','number'),f('cost_per_litre','number'),f('business_date','date')]} onSave={async v=>{if(window.confirm('Verify the received quantity and post this delivery?'))await save('/deliveries',v)}} busy={busy}/><p className="muted">Only verified deliveries should be posted. Tank stock updates immediately.</p></section>}
 {tab==='Daily close'&&station&&<><section className="card formcard"><h2>Review the business day</h2><EntryForm fields={dayFields} onSave={async v=>run(async()=>setPreview(await request('/daily-close/preview',{...v,station_id:Number(station)})))} button="Check readiness" busy={busy}/>{preview&&<><h3>{preview.blockers.length?'Before closing':'Ready to close'}</h3>{preview.blockers.map((b:string)=><p className="warning" key={b}>{b}</p>)}<p>Sales GHS {money(preview.summary.expected)} · Expenses GHS {money(preview.summary.expenses)} · Variance GHS {money(preview.summary.variance)}</p><Table rows={preview.inventory} columns={['tank','expected_closing','physical_closing','variance']}/>{['owner','manager'].includes(user.role)&&<button disabled={busy||preview.blockers.length>0} onClick={()=>{if(window.confirm('Close and lock this business day?'))save('/daily-close',{station_id:Number(station),business_date:preview.summary.date})}}>Close and lock day</button>}</>}</section><section className="card"><h2>Business-day history</h2><Table rows={days} columns={['business_date','status','revision','closed_at']}/></section>{owner&&<section className="card formcard"><h2>Reopen the latest closed day</h2><EntryForm fields={[f('business_date','date'),f('reason')]} onSave={async v=>{if(window.confirm('Reopen this day for corrections?')){await save('/daily-close/reopen',{...v,station_id:Number(station)});setPreview(null)}}} button="Authorize reopening" busy={busy}/></section>}</>}
 {tab==='Maintenance'&&station&&<><section className="card"><h2>Equipment register</h2><Table rows={equipment} columns={['id','name','category','status','next_service_date']}/></section><section className="card"><h2>Maintenance jobs</h2><Table rows={maintenance} columns={['id','equipment_id','fault','technician','status','cost','next_service_date']} actions={r=>r.status!=='completed'&&['owner','manager'].includes(user.role)?<button onClick={()=>setEditRepair(r)}>Complete repair</button>:null}/></section>{editRepair&&<section className="card formcard"><h2>Complete job #{editRepair.id}</h2><EntryForm fields={[f('repair','textarea'),f('technician'),f('cost','number'),f('next_service_date','date',true),f('business_date','date')]} onSave={async v=>{await save(`/maintenance/${editRepair.id}/complete`,v);setEditRepair(null)}} busy={busy}/></section>}{['owner','manager'].includes(user.role)&&<section className="card formcard"><h2>Add equipment</h2><EntryForm fields={[f('name'),pick('category',options(['pump','nozzle','tank','generator','pos','fire_extinguisher','other'])),pick('nozzle_id',data.nozzles||[],true),f('next_service_date','date',true)]} onSave={v=>save('/equipment',{...v,station_id:Number(station)})} busy={busy}/></section>}{ops&&<section className="card formcard"><h2>Report a maintenance job</h2><EntryForm fields={[pick('equipment_id',equipment),f('fault','textarea'),f('technician','text',true)]} onSave={v=>save('/maintenance',v)} busy={busy}/></section>}</>}
 {tab==='Incidents'&&station&&<><section className="card"><h2>Incident register</h2><Table rows={incidents} columns={['id','category','severity','description','status','resolution']} actions={r=>r.status==='open'&&ops?<button onClick={()=>{const resolution=window.prompt('Record the resolution');if(resolution)save(`/incidents/${r.id}/resolve`,{resolution})}}>Resolve</button>:null}/></section>{(ops||user.role==='attendant')&&<section className="card formcard"><h2>Report an incident</h2><EntryForm fields={[pick('category',options(['pump_malfunction','tank_issue','fuel_spill','power_outage','pos_problem','customer_complaint','safety_issue','transaction_anomaly','other'])),pick('severity',options(['low','medium','high','critical'])),f('description','textarea')]} onSave={v=>save('/incidents',{...v,station_id:Number(station)})} busy={busy}/></section>}</>}
 {tab==='Reports'&&station&&<section className="card"><h2>Station reports</h2><div className="filters"><label>Report<select value={kind} onChange={e=>{setKind(e.target.value);setReport(null)}}>{['daily','sales','inventory','expenses','deliveries','credit','maintenance','management'].map(k=><option key={k}>{k}</option>)}</select></label><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>{kind==='sales'&&<div className="filters"><label>Nozzle<select value={filterNozzle} onChange={e=>setFilterNozzle(e.target.value)}><option value="">All</option>{data.nozzles?.map((n:Row)=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label>Fuel<select value={filterFuel} onChange={e=>setFilterFuel(e.target.value)}><option value="">All</option>{data.products?.map((p:Row)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Attendant ID<input type="number" min="1" value={filterAttendant} onChange={e=>setFilterAttendant(e.target.value)}/></label><label>Payment method<select value={filterPayment} onChange={e=>setFilterPayment(e.target.value)}><option value="">All</option>{['cash','momo','card','credit'].map(k=><option key={k}>{k}</option>)}</select></label></div>}<div className="actions"><button disabled={busy} onClick={loadReport}>Run report</button>{['csv','xlsx','pdf'].map(fmt=><button className="secondary" key={fmt} disabled={busy} onClick={()=>download(fmt)}>Export {fmt.toUpperCase()}</button>)}</div>{report&&<><p className="muted">{report.basis}</p><Table rows={report.rows} columns={Object.keys(report.rows[0]||{})}/><div className="totals">{Object.entries(report.totals).map(([k,v])=><span key={k}>{label(k)}: <strong>{money(v)}</strong></span>)}</div></>}</section>}
 {tab==='Staff'&&station&&owner&&<><section className="card"><h2>Staff access</h2><Table rows={staff} columns={['id','name','email','role','active']} actions={r=><button onClick={()=>{const reason=window.prompt('Reason for this access change');if(reason)save(`/staff/${r.id}/access`,{active:!r.active,reason})}}>{r.active?'Disable':'Enable'}</button>}/></section><section className="card formcard"><h2>Add a staff account</h2><EntryForm fields={[f('name'),f('email','email'),f('password','password'),pick('role',options(['manager','supervisor','attendant','accountant','auditor']))]} onSave={v=>save('/staff',{...v,station_id:Number(station)})} busy={busy}/></section><section className="card formcard"><h2>Reset a staff password</h2><EntryForm fields={[pick('user_id',staff),f('password','password'),f('reason')]} onSave={async v=>{const id=v.user_id;delete v.user_id;await save(`/staff/${id}/password`,v)}} busy={busy}/></section></>}
 {tab==='Audit log'&&owner&&<section className="card"><h2>Recent audit history</h2><Table rows={auditRows} columns={['created','user_id','action','details']}/></section>}
 {tab==='Settings'&&owner&&<section className="card formcard"><h2>Station configuration</h2><label>Register<select value={config} onChange={e=>setConfig(e.target.value)}>{Object.keys(settingForms).map(k=><option key={k}>{k}</option>)}</select></label><EntryForm key={config+station} fields={settingForms[config].fields} onSave={async values=>run(async()=>{await request(settingForms[config].path,config==='Station'?values:{...values,station_id:Number(station)});if(config==='Station'){const rows=await request('/stations');setStations(rows);setStation(String(rows.at(-1).id));}else await refresh();setMessage(`${config} saved.`)})} button={`Add ${config.toLowerCase()}`} busy={busy||(!station&&config!=='Station')}/></section>}
 </main></div>
}
