from alembic import op
import sqlalchemy as sa
revision='0001'
down_revision=None
branch_labels=None
depends_on=None
def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=60), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_station_id'), 'expenses', ['station_id'], unique=False)
    op.create_table('fuel_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_products_station_id'), 'fuel_products', ['station_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tanks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('capacity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reorder', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['fuel_products.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tanks_station_id'), 'tanks', ['station_id'], unique=False)
    op.create_table('fuel_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('supplier', sa.String(length=120), nullable=False),
    sa.Column('waybill_litres', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('received_litres', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('cost_per_litre', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'reference')
    )
    op.create_index(op.f('ix_fuel_deliveries_station_id'), 'fuel_deliveries', ['station_id'], unique=False)
    op.create_table('nozzles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('meter', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nozzles_station_id'), 'nozzles', ['station_id'], unique=False)
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('nozzle_id', sa.Integer(), nullable=False),
    sa.Column('attendant_id', sa.Integer(), nullable=False),
    sa.Column('opening', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('closing', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('litres', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('expected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('momo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('card', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('variance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzles.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_station_id'), 'shifts', ['station_id'], unique=False)
    # ### end Alembic commands ###
def downgrade():
    raise RuntimeError('Financial schemas require an explicit restore, not destructive downgrades')
