from alembic import op
import sqlalchemy as sa
revision='0002'
down_revision='0001'
branch_labels=None
depends_on=None
def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_buckets',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact', sa.String(length=120), nullable=False),
    sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('terms_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('credit_limit >= 0 AND terms_days >= 0', name='ck_customer_terms'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_station_id'), ['station_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('business_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('closed_by', sa.Integer(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'business_date')
    )
    with op.batch_alter_table('business_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_days_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_days_station_id'), ['station_id'], unique=False)

    op.create_table('customer_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_customer_payment_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'reference')
    )
    with op.batch_alter_table('customer_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_payments_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_payments_station_id'), ['station_id'], unique=False)

    op.create_table('customer_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('registration', sa.String(length=40), nullable=False),
    sa.Column('fuel_product_id', sa.Integer(), nullable=False),
    sa.Column('litre_limit', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['fuel_product_id'], ['fuel_products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'registration')
    )
    with op.batch_alter_table('customer_vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_vehicles_customer_id'), ['customer_id'], unique=False)

    op.create_table('fuel_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('previous_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['fuel_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fuel_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fuel_prices_product_id'), ['product_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.String(length=1000), nullable=False),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_station_id'), ['station_id'], unique=False)

    op.create_table('mfa_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest')
    )
    with op.batch_alter_table('mfa_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mfa_recovery_codes_user_id'), ['user_id'], unique=False)

    op.create_table('mfa_steps',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('daily_close_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['business_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tank_id', 'source', 'reference')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_movements_tank_id'), ['tank_id'], unique=False)

    op.create_table('tank_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('tank_id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('physical', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('expected', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('variance', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['tank_id'], ['tanks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tank_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tank_readings_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tank_readings_station_id'), ['station_id'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nozzle_id', sa.Integer(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['nozzle_id'], ['nozzles.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nozzle_id')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_station_id'), ['station_id'], unique=False)

    op.create_table('credit_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('registration', sa.String(length=40), nullable=False),
    sa.Column('driver', sa.String(length=120), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('litres', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount > 0 AND litres > 0', name='ck_credit_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['customer_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'reference')
    )
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_transactions_business_date'), ['business_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_transactions_station_id'), ['station_id'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('fault', sa.String(length=500), nullable=False),
    sa.Column('technician', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('repair', sa.String(length=1000), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('cost >= 0', name='ck_maintenance_cost'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_records_station_id'), ['station_id'], unique=False)

    op.create_table('payment_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('charge_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_allocation_positive'),
    sa.ForeignKeyConstraint(['charge_id'], ['credit_transactions.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['customer_payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', 'charge_id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_charge_id'), ['charge_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), server_default='pending', nullable=False))
        batch_op.add_column(sa.Column('recorded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_expenses_business_date'), ['business_date'], unique=False)
        batch_op.create_foreign_key('fk_operations_0', 'users', ['approved_by'], ['id'])
        batch_op.create_foreign_key('fk_operations_1', 'users', ['recorded_by'], ['id'])

    with op.batch_alter_table('fuel_deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_fuel_deliveries_business_date'), ['business_date'], unique=False)

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('business_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_shifts_business_date'), ['business_date'], unique=False)
        batch_op.create_index('uq_active_nozzle_shift', ['nozzle_id'], unique=True, postgresql_where=sa.text("status IN ('open','submitted')"), sqlite_where=sa.text("status IN ('open','submitted')"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('mfa_secret', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###
    with op.batch_alter_table('fuel_products') as batch_op:
        batch_op.create_check_constraint('ck_product_price', 'price > 0')
    with op.batch_alter_table('tanks') as batch_op:
        batch_op.create_check_constraint('ck_tank_volume', 'capacity > 0 AND stock >= 0 AND stock <= capacity AND reorder >= 0 AND reorder <= capacity')
    with op.batch_alter_table('nozzles') as batch_op:
        batch_op.create_check_constraint('ck_nozzle_meter', 'meter >= 0')
    with op.batch_alter_table('shifts') as batch_op:
        batch_op.create_check_constraint('ck_shift_meter', 'closing IS NULL OR closing >= opening')
    with op.batch_alter_table('shifts') as batch_op:
        batch_op.create_check_constraint('ck_shift_amounts', 'cash >= 0 AND momo >= 0 AND card >= 0 AND credit >= 0 AND litres >= 0 AND price > 0')
    with op.batch_alter_table('fuel_deliveries') as batch_op:
        batch_op.create_check_constraint('ck_delivery_amounts', 'received_litres > 0 AND waybill_litres > 0 AND cost_per_litre > 0')
    with op.batch_alter_table('expenses') as batch_op:
        batch_op.create_check_constraint('ck_expense_amount', 'amount > 0')
    connection=op.get_bind()
    connection.execute(sa.text("UPDATE shifts SET business_date = date(started) WHERE business_date IS NULL"))
    connection.execute(sa.text("UPDATE expenses SET business_date = date(created), status = 'approved' WHERE business_date IS NULL"))
    connection.execute(sa.text("UPDATE fuel_deliveries SET business_date = CURRENT_DATE, created = CURRENT_TIMESTAMP WHERE business_date IS NULL"))
    for name in ['shifts','expenses','fuel_deliveries']:
        with op.batch_alter_table(name) as batch_op:
            batch_op.alter_column('business_date', existing_type=sa.Date(), nullable=False)
    with op.batch_alter_table('fuel_deliveries') as batch_op:
        batch_op.alter_column('created', existing_type=sa.DateTime(timezone=True), nullable=False)
    # Prior delivery dates were not captured. Preserve stock as an explicit migration baseline.
    connection.execute(sa.text("INSERT INTO stock_movements (station_id,tank_id,business_date,quantity,source,reference,created) SELECT station_id,id,CURRENT_DATE,stock,'migration_opening','legacy',CURRENT_TIMESTAMP FROM tanks"))
    if connection.dialect.name == 'postgresql':
        op.execute("CREATE FUNCTION fuelflow_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Financial history is append-only'; END $$")
        for table in ['audit_logs','daily_close_events','stock_movements','credit_transactions','customer_payments','payment_allocations','fuel_prices']:
            op.execute(f"CREATE TRIGGER immutable_{table} BEFORE UPDATE OR DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION fuelflow_immutable()")
    else:
        for table in ['audit_logs','daily_close_events','stock_movements','credit_transactions','customer_payments','payment_allocations','fuel_prices']:
            for action in ['UPDATE','DELETE']:
                op.execute(f"CREATE TRIGGER immutable_{table}_{action} BEFORE {action} ON {table} BEGIN SELECT RAISE(ABORT, 'Financial history is append-only'); END")

def downgrade():
    raise RuntimeError('Financial schemas require an explicit restore, not destructive downgrades')
